#app端口
port: 8080
appName: oneGPT
log:
  level: DEBUG

#################################
mysql:
  default:
    addr: "127.0.0.1:3306"
    database: demo
    user: "user"
    password: "pwd"

redis:
  default:
    addr: "127.0.0.1:6379"
    password: ""
    db: 1
